### PR TITLE
Use docker to build and deploy deb package

### LINKED ISSUE #101: "/usr/bin/python: No module named mssqlcli"
I've followed the installation instructions and when I try to run `mssql-cli` I get the subject error message.

Installation went OK so I am not sure what is wrong? I'm using Ubuntu 17.10

```
joakim@XPS:~$ pip install mssql-cli
Requirement already satisfied: mssql-cli in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: cli-helpers<1.0.0,>=0.2.3 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: click>=4.1 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: enum34>=1.1.6 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: wheel>=0.29.0 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: prompt-toolkit<1.1.0,>=1.0.10 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: applicationinsights>=0.11.1 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: humanize>=0.5.1 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: sqlparse<0.3.0,>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from mssql-cli)
Requirement already satisfied: backports.csv>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from cli-helpers<1.0.0,>=0.2.3->mssql-cli)
Requirement already satisfied: terminaltables>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from cli-helpers<1.0.0,>=0.2.3->mssql-cli)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->mssql-cli)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<1.1.0,>=1.0.10->mssql-cli)
```

### PR DESCRIPTION
**Pull request by ellbosch**
Closes #101 and #257. Completes Debian work for #383. And closes PR #416 in favor of this one.

List of changes include:
1. **Packaging mssql-cli into .deb.** This PR produces a Debian package of mssql-cli using Docker. The package has run successfully in limited testing across Ubuntu 16.04 and 18.04, using both Docker containers and VMs.
2. **Support for automated releases in Azure DevOps Pipelines.** Using a test pipeline, I have validated that we are able to build a .deb, publish to daily storage, and download and run mssql-cli. We did this by creating a `publish_daily_deb` script in our `release.py`.
3. **Updated docs.** Documentation has been updated for building and publishing a .deb of mssql-cli in Docker.

Hopefully this implementation will prevent headaches for anyone who works on this in the future :)

### CODE REVIEW

File: build_scripts/debian/build.sh [hunk 1]
```diff
@@ -57,9 +57,13 @@ make install
 export CUSTOM_PYTHON=$source_dir/python_env/bin/python3
 export CUSTOM_PIP=$source_dir/python_env/bin/pip3
 
+# Download dependencies needed to run build stage
+$source_dir/python_env/bin/python3 -m pip install --upgrade pip
+$source_dir/python_env/bin/python3 -m pip install -r $source_dir/requirements-dev.txt
```
Comment (pensivebrian) [inline build_scripts/debian/build.sh]: Calling `build.py build` below does the same action, running pip install requirements-dev.txt. Can we remove these two lines?

Comment (ellbosch) [reply build_scripts/debian/build.sh]: `build.py` will not upgrade `pip`. Furthermore, we get import errors because `build.py` lacks the dependencies in the first place to process the request. It's a bit of a catch 22. So we really need both here.

Comment (pensivebrian) [reply build_scripts/debian/build.sh]: Not thrilled about shipping the dev packages. If this works, let's leave it for now, but create a work item to fix this.
